name: Immortalwrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run make.sh
        run: |
          sudo chmod +x make.sh
          sudo ./make.sh
      
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: immortalwrt
          artifacts: "*.img.gz"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
