name: Immortalwrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}


    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          
      - name: Checkout
        uses: actions/checkout@main

      - name: Run builder.sh
        run: sh builder.sh
      
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: immortalwrt
          artifacts: "*.img.gz"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
